### ISSUE TITLE
unable to install typings

### ISSUE THREAD

**Issue by jimjones26** [types/rethinkdbdash#4]
npm install @types/rethinkdbdash --save-d

throws a not found error, am I doing something wrong?

**Comment by marshall007** [comment]
@jimjones26 until the long awaited https://github.com/Microsoft/types-publisher/issues/4 lands you need to reference these typings from GitHub (see https://github.com/types/rethinkdbdash/issues/1#issuecomment-308442936 for the explanation). For now just do:

```
npm install types/rethinkdbdash --save-dev
```

... which will reference it as a git dependency in your `package.json`.

**Comment by jimjones26** [comment]
Thank you for the quick reply! That worked
